PROJ_BASE := ..
include $(PROJ_BASE)/makefile.libs

TARGET_TYPE := EXE
TARGET := Test

INC += $(INC_MOSS) $(INC_GTEST)
LIB_DIR += $(LIB_DIR_GTEST)
LIB += $(LIB_GTEST)

include $(PROJ_BASE)/makefile.moss
