PROJ_BASE := ../../
include $(PROJ_BASE)/makefile.libs

TARGET_TYPE := EXE
TARGET := TestServer

INC += $(INC_MOSS) $(INC_TEST_PROTO)
LIB := $(LIB_TEST_PROTO) $(LIB_MOSS) $(LIB)

include $(PROJ_BASE)/makefile.moss
