name: C/C++ CI

on: 
  push:
    branches:
    - master
  schedule:
  - cron: 0 2 * * 1-5

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: cd src && make
